"""
	Creating 'series' with Pandas.
	Series are a data structure where you obtain a table as a column pair of the data row with its index that is automatically generated by Series object.
    You can add your custom index matching every data row in your Series object.
"""

import pandas as pd




"""Series dataset"""
red = 'red'
green = 'green'
yellow = 'yellow'

# We have a list of apples in different colors
apples = [red, red, green, red, yellow, green, red, yellow, yellow, green, yellow, red, yellow]

# Transform the list of apples to a pd.Series data structure
apples_series = pd.Series(apples)

print(apples_series)



"""Series dataset with custom index"""
john = 'John'
joseph = 'Joseph'
jennifer = 'Jennifer'
carlos = 'Carlos'
berenice = 'Berenice'
lili = 'Lili'
linda = 'Linda'
andrew = 'Andrew'
javier = 'Javier'

users = [john, joseph, jennifer, carlos, berenice, lili, linda, andrew, javier]

users_series = pd.Series(data=users, index=['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I'])

print(users_series)